
model_verbosity = "low"
model = "gpt-5-codex"
model_reasoning_effort = "medium"

[features]
web_search_request = true

[projects."/Users/jfokkan/Developer/notes/coveo-work-notes"]
trust_level = "trusted"

[projects."/Users/jfokkan/Developer/jonfk_code/yt-power-subscriber"]
trust_level = "trusted"

[projects."/Users/jfokkan/Developer/jonfk_code/basecoat_llm.txt"]
trust_level = "trusted"

[projects."/Users/jfokkan/Developer/jonfk_code/basecoat"]
trust_level = "trusted"

[projects."/Users/jfokkan/Developer/jonfk_code/video-download-srv"]
trust_level = "trusted"

[projects."/Users/jfokkan/Developer/Coveo_code/searchapi2"]
trust_level = "trusted"

[projects."/Users/jfokkan/Developer/jonfk_code/utility-belt"]
trust_level = "trusted"

[projects."/Users/jfokkan/Developer/jonfk_code/draft-automata"]
trust_level = "trusted"

[projects."/Users/jfokkan/Developer/jonfk_code/recipes"]
trust_level = "trusted"

[projects."/Users/jfokkan/Developer/Coveo_code/search-usage-metrics"]
trust_level = "trusted"

[projects."/Users/jfokkan/Developer/Coveo_code/coveo-scala-commons"]
trust_level = "trusted"

[projects."/Users/jfokkan/Developer/Coveo_code/innovate/relevance-debugger"]
trust_level = "trusted"
